image: node:alpine
stages:
 - build
#  - push
 
build-job:
 stage: build
 tags:
  - test-runner
 image: docker
 script:
  - docker build -t helloapp .
  - if [ $(docker ps -aq --filter name=helloapp) ]; then docker rm -f helloapp;fi
  - docker run -d -p 8080:80 helloapp 

# push-job:
#  stage: push
#   tags:
  
# ## 构建镜像
# .build-docker:
#   stage: buildimage
#   script:
#     # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWD  $CI_REGISTRY
#     # - docker build -t ${IMAGE_NAME} -f ${DOCKER_FILE_PATH} .
#     # - docker push ${IMAGE_NAME} 
#     # - docker rmi ${IMAGE_NAME} 
#     - docker login -u admin -p daocloud  10.7.253.201
#     - docker build -t helloapp -f ${DOCKER_FILE_PATH} .
#     - docker push ${IMAGE_NAME} 
#     - docker rmi ${IMAGE_NAME} 
#   rules:
#     - if: " $RUN_BUILD_IMAGE == 'no' "
#       when: never
#     - when: always