image: node:alpine
    job_deploy:
        stage: deploy
        image: docker
        tags:
            - vite
        script:
            - docker build -t helloapp .
            - if [ $(docker ps -aq --filter name=myvite-container) ]; then docker rm -f myvite-container;fi
            - docker run -d -p 8080:80 --name 