image: node:alpine
stages:
 - build_image
 - push_image
 
before_script:
 - docker info
 - docker login -u "admin" -p "daocloud" 10.7.253.201
 
build_image:
 stage: build_image
 script:
  - docker build --pull -t "10.7.253.201/xhope-test/helloapp:1.0" .
  
push_image:
 stage: push_image
 script:
  - docker push "10.7.253.201/xhope-test/helloapp:1.0"
  - docker rmi "10.7.253.201/xhope-test/helloapp:1.0"
